spring:
  application:
    name: wallet

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  management:
    endpoints:
      web:
        exposure:
          include: refresh